# MCCarnival-PPT 插件配置文件

# PPT页数设置
ppt:
  # PPT的最大页数，超过此数值只能通过 /post set 命令修改
  max-page: 100
  
# 支持的物品类型配置
supported-items:
  # 物品类型列表，支持多种不同的物品进行CustomModelData切换
  # 格式：- "MATERIAL_NAME"
  - "PHANTOM_MEMBRANE"
  - "PAPER"
  - "BOOK"
  - "WRITTEN_BOOK"

# PPT翻页笔配置
pagepen:
  # 翻页笔物品类型
  material: "RED_DYE"
  # 翻页笔显示名称
  display-name: "§6PPT翻页笔"
  # 翻页笔CustomModelData值
  custom-model-data: 1
  # 翻页笔说明文字
  lore:
    - "§7左键: 下一页"
    - "§7右键: 上一页"
    - "§7用于控制ppt的页码"
  


# 其他设置
settings:
  # 搜索范围（格数）
  search-range: 10